### ISSUE TITLE
Error: Invalid Attribute Value Match 

### ISSUE THREAD

**Issue by yankcrime** [xunleii/terraform-module-k3s#104]
At some point the accepted values for `allowed_uses` with the `tls_self_signed_cert` resource changed, and when using the currently released version of this module Terraform errors with an `Error: Invalid Attribute Value Match`.  This was fixed in e160154f94704d72633c4bad3ac5e23bc287ac99 but this commit is not included in the most recent release.

Can you please release an updated version of this module which includes this fix (plus probably others)?

**Comment by richard-fairthorne** [comment]
> Can you please release an updated version of this module which includes this fix (plus probably others)?

This module cannot deploy k3s without that commit. +1

**Comment by richard-fairthorne** [comment]
Workaround:

```terraform
module "k3s" {
  source  = "github.com/xunleii/terraform-module-k3s?ref=a8e8f04fd25feb7ab5236233daa5ebcc3a6baef3"
  # insert the 2 required variables here
}
```

**Comment by xunleii** [comment]
Hi @yankcrime & @richard-fairthorne, I will try to make a release today. I totally forgot to make a release after the last PR merged, sorry for that

**Comment by richard-fairthorne** [comment]
Much appreciated!
