### ISSUE TITLE
Error "Variable `name` is deprecated"

### ISSUE THREAD

**Issue by Joao-1** [xunleii/terraform-module-k3s#136]
Hello! 

I'm trying to set up a simple cluster in EC2 instance, but ever have the same problem executing ```terraform plan```:

![image](https://github.com/xunleii/terraform-module-k3s/assets/58475277/ee0f7b6c-83f3-46a3-999a-3b9fe8f64105)

I used my own configuration and the example one in the readme, but both result in same error message. 

Do you know what it could be?

**Comment by xunleii** [comment]
Hello @Joao-1, thank you for your problem.
This is a problem in the README.md, which was not updated after the `name` was made obsolete.

You should use `cluster_domain` instead of `name`.
