### ISSUE TITLE
Taking a node out of the configuration keeps the node within the cluster but cordoned

### ISSUE THREAD

**Issue by laurentiusoica** [xunleii/terraform-module-k3s#139]
I have a total of four nodes in my K3S cluster, where three of them function as both master and worker nodes, and the 4th node serves as a worker node.

When I adjust the configuration to exclude the 4th node and then run 'terraform apply,' the 4th node is cordoned but remains in the K3S cluster with K3S still operational on it.

```
$ terraform apply
module.k3s.null_resource.agents_drain["node-4"] (remote-exec): node/node-4 drained
module.k3s.null_resource.agents_drain["node-4"]: Destruction complete after 1s
module.k3s.null_resource.agents_install["node-4"]: Destroying... [id=788767868902175907]
module.k3s.null_resource.agents_install["node-4"]: Destruction complete after 0s

Apply complete! Resources: 0 added, 0 changed, 3 destroyed.
```

```
$ kubectl get nodes -A -w
NAMESPACE   NAME     STATUS                     ROLES                       AGE     VERSION
            node-1   Ready                      control-plane,etcd,master   3h31m   v1.28.1+k3s1
            node-2   Ready                      control-plane,etcd,master   3h31m   v1.28.1+k3s1
            node-3   Ready                      control-plane,etcd,master   3h31m   v1.28.1+k3s1
            node-4   Ready,SchedulingDisabled   <none>                   3h31m    v1.28.1+k3s1
```

**Comment by xunleii** [comment]
I think this is "known" behavior. Did you run this command just after deleting the 4th node?

If so, it takes ~30s (at least on my end) to change its state from `Ready` to `NotReady` when the node is deleted. 
This is normal, because if a node cannot contact another control-plane, it may be a simple restart of that node that will join the pool when k3s is started.

However, I agree that this node should be deleted by this module, but for reasons of "security" (and ease above all), only the agents will be deleted. I prefer to let the user manage control-plane deletion.

**Comment by xunleii** [comment]
> The node-4 remains in Ready state:
> ```
> $ date; kubectl get nodes |grep node-4
> Wed Sep 20 08:27:50 UTC 2023
> node-4   Ready,SchedulingDisabled   <none>                      5m43s   v1.27.5+k3s1
> $ date; kubectl get nodes |grep node-4
> Wed Sep 20 08:38:33 UTC 2023
> node-4   Ready,SchedulingDisabled   <none>                      16m   v1.27.5+k3s1
> ```
> 
> in my case this "node-4" is an agent node that had this configuration:
> ```
>   agents = {
>       # The node name will be automatically provided by
>       # the module using the field name... any usage of
>       # --node-name in additional_flags will be ignored
>       node-4 = {
>           ip = ""
>           connection = {
>             host = "" // public node IP
>             user = "ubuntu"
>             private_key = "${file(var.sshkey)}"
>           }
>           labels = {"node.kubernetes.io/pool" = "service-pool"}
>       },
>   } 
> ```

Hi @laurentiusoica, sorry for the delay, I didn't have enough spare time to respond to you before.

So, if I can summarize this issue in a few words, when a node is removed from this module (worker only), it must be drain then removed from the node pool. It is right?

If so, it can be implemented relatively easily by adding a simple `kubectl delete node X` on the resource in charge of the drain. I just need to check if TF run all commands even if a previous one fails, to avoid removing a node where the drain has been successfully done.

I probably do that this weekend, I'll keep you posted.

**Comment by laurentiusoica** [comment]
@xunleii right, it is about removing the node from the k8s cluster. But then it's also about uninstalling k3s from that node. Is this already covered ?

**Comment by xunleii** [comment]
> @xunleii right, it is about removing the node from the k8s cluster. But then it's also about uninstalling k3s from that node. Is this already covered ?
> 

Currently not, but can be done I think. When we install k3s using the official script, it also installs an uninstall script, so I think it can be used too. I will see how it can be implemented
