### ISSUE TITLE
Refresh kubeconfig when terraform state is lost

### ISSUE THREAD

**Issue by alita1991** [xunleii/terraform-module-k3s#142]
Hi,

I have a scenario, where I need to refresh the local kubeconfig with the one from the target host. Right now, terraform does not offer a way to copy a remote file to the local host. 

https://github.com/hashicorp/terraform/issues/3379

Is there a way to refresh the kubeconfig with the current module if I lose the tfstate or any other alternative solution that can be automated via terraform?

Thanks

**Comment by xunleii** [comment]
Hi @alita1991, the only way I can found today is using the [external](https://registry.terraform.io/providers/hashicorp/external/latest/docs/data-sources/external) provider which allows you to make what you want and expose any information to Terraform (like a shell script that `cat | sed` the kubeconfig remotely).

**Comment by alita1991** [comment]
Hi, sadly, the **external** provider does not allow the user to SSH directly, I decided to pick a module developed by the community called **terraform-provider-ssh**, which does what I need.
