### ISSUE TITLE
Servers must have an odd number of nodes

### ISSUE THREAD

**Issue by slavb18** [xunleii/terraform-module-k3s#172]
Trying to create HA k3s cluster based on https://docs.k3s.io/datastore/ha:

`Two or more server nodes that will serve the Kubernetes API and run other control plane services`

But I cannot create two nodes becouse of:

```
  validation {
    condition     = length(var.servers) % 2 == 1
    error_message = "Servers must have an odd number of nodes."
  }
```
https://github.com/xunleii/terraform-module-k3s/blob/79185d3ae24f6223d44c53bb24b74ac81775478a/variables.tf#L91

Why modules restricts even server nodes count?

**Comment by xunleii** [comment]
Hi @slavb18,

This module was originally designed to run `k3s` with the embedded ETCD server, where an odd number of nodes is recommended (https://docs.k3s.io/datastore/ha-embedded and https://etcd.io/docs/v3.3/faq/#what-is-failure-tolerance).

I assume that you are using an external database, a case that was not foreseen by this module. Unfortunately, Terraform does not currently allow the use of several different variables in the validation block and I don't want to "break" this validation to avoid possible problems with ETCD with people who are new to Kubernetes.

In your case, I recommend using the fork you've made for the PR #173.

Nevertheless, thank you for your contribution.
