### ISSUE TITLE
Make it possible to have additional flags per agent

### ISSUE THREAD

**Issue by tedsteen** [xunleii/terraform-module-k3s#18]
It's not possible to pass additional agent flags per agent at the moment.
This becomes a problem when using a cloud-controller-manager, as each worker node need the `provider-id` to be set to the specific agents id, see [here](https://medium.com/@kmcgrath/k3s-in-the-cloud-10b7af70f50b) for example.

**Comment by xunleii** [comment]
Thank for your issue (and for your PR), I will review it ASAP.
