### ISSUE TITLE
Server taints flags are not used

### ISSUE THREAD

**Issue by tedsteen** [xunleii/terraform-module-k3s#20]
`server_taints_flags` over [here](https://github.com/xunleii/terraform-module-k3s/blob/master/server_node.tf#L11) is never used.
They should be included in the trigger and in the install command.

**Comment by xunleii** [comment]
Thanks you for reporting this forgets.
There are some mistakes in this module. I will try to rewrite this module soon in order to fix other problems too (TF warnings, reseting the server when labels change, ...).
