### ISSUE TITLE
Windows Terraform - SSH authentication failed

### ISSUE THREAD

**Issue by tinohager** [xunleii/terraform-module-k3s#43]
Hi i try to create a k3s cluster on hetzner cloud with this terraform script, the script run in a timeout on connect the machine over ssh. I tried to manually create a server and assign the key so the key worked fine. But when I start the script, unfortunately it does not work where to look for the private key?

> Error: timeout - last error: SSH authentication failed (root@XXX.XXX.XXX.XXX:22): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain

> module.k3s.null_resource.k8s_ca_certificates_install[0] (remote-exec): Connecting to remote host via SSH...
module.k3s.null_resource.k8s_ca_certificates_install[0] (remote-exec):   Host: XXX.XXX.XXX.XXX
module.k3s.null_resource.k8s_ca_certificates_install[0] (remote-exec):   User: root
module.k3s.null_resource.k8s_ca_certificates_install[0] (remote-exec):   Password: false
module.k3s.null_resource.k8s_ca_certificates_install[0] (remote-exec):   Private key: false
module.k3s.null_resource.k8s_ca_certificates_install[0] (remote-exec):   Certificate: false
module.k3s.null_resource.k8s_ca_certificates_install[0] (remote-exec):   SSH Agent: false
module.k3s.null_resource.k8s_ca_certificates_install[0] (remote-exec):   Checking Host Key: false

My windows commands to generate a key
```
# Change the Windows Service config for "OpenSSH Authentication Agent"
sc config "ssh-agent" start=delayed-auto
sc start "ssh-agent"

# Create a private/public key pair
ssh-keygen -t ecdsa -b 521 -f myKey

ssh-add myKey
```

**Comment by xunleii** [comment]
I don't know why Terraform don't use your SSH agent :thinking: ... Just to be sure, your k3s instance are instantiated with your public key, right ?

Also, if I remember, SSH agent is only available with Pagent on Windows (cf. https://www.terraform.io/docs/language/resources/provisioners/connection.html#agent), so I don't understand why it works for other instances.

I'm sorry, I never use Terraform on Windows directly (only on WSL), so I don't know how to resolve this issue :(

**Comment by tinohager** [comment]
I have try now with `Pagent` i can connect with putty over pagent (without password) but it not work with terraform.

**Comment by tinohager** [comment]
I have installed an ubuntu on my windows machine with WSL2. But i have the same error...

> Error: timeout - last error: SSH authentication failed (root@XXX.XXX.XXX.XXX:22): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain

```
ssh-keygen
more /root/.ssh/id_rsa.pub

curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
apt install terraform
git clone https://github.com/xunleii/terraform-module-k3s.git
cd terraform-module-k3s/examples/hcloud-k3s/
terraform init
terraform apply
```

**Comment by xunleii** [comment]
I don't see why it is not working. As I see, your are using the given example.

Have you something like that when you use WSL ?
> module.k3s.null_resource.k8s_ca_certificates_install[0] (remote-exec): Connecting to remote host via SSH...
> module.k3s.null_resource.k8s_ca_certificates_install[0] (remote-exec): Host: XXX.XXX.XXX.XXX
> module.k3s.null_resource.k8s_ca_certificates_install[0] (remote-exec): User: root
> module.k3s.null_resource.k8s_ca_certificates_install[0] (remote-exec): Password: false
> module.k3s.null_resource.k8s_ca_certificates_install[0] (remote-exec): Private key: false
> module.k3s.null_resource.k8s_ca_certificates_install[0] (remote-exec): Certificate: false
> **module.k3s.null_resource.k8s_ca_certificates_install[0] (remote-exec): SSH Agent: true**
> module.k3s.null_resource.k8s_ca_certificates_install[0] (remote-exec): Checking Host Key: false

If yes, running the following commands can solve your problem ?

```shell
git clone https://github.com/xunleii/terraform-module-k3s.git
cd terraform-module-k3s/examples/hcloud-k3s/

ssh-keygen -f hcloud.id_rsa
ssh-add hcloud.id_rsa
terraform init
terraform apply --var ssh_key="$(cat hcloud.id_rsa.pub)"
```

**Comment by tinohager** [comment]
Thanks for your support I won't be back in the office until Monday then I will review your suggestion.

**Comment by tinohager** [comment]
First i have this error `Could not open a connection to your authentication agent.` 
I execute this `eval "$(ssh-agent)"`

After that i have problems with the certificates

```
Error: Post "https://XX.XX.XX.XX:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings": x509: certificate signed by unknown authority

Error: Post "https://XX.XX.XX.XX:6443/api/v1/namespaces/default/serviceaccounts": x509: certificate signed by unknown authority
```

**Comment by xunleii** [comment]
Thanks for your help. Firstly, good news, your cluster is provisioned. But in fact, this certificates error is really weird and should not occurs. Have you change something on any `example/hcloud-k3s` ? 

Can you try this inside the directory `example/hcloud-k3s` ?
```
# add output with the generated kubeconfig
cat <<EOF >> outputs.tf

output "kubeconfig" {
  value = module.k3s.kube_config
}
EOF

# generate the kubeconfig
terraform output kubeconfig --raw > kubeconfig

# test if you can access on your side
KUBECONFIG=./kubeconfig kubectl version
```

I think, you will have the same certificates problem.

**Comment by tinohager** [comment]
Hi, i have reset my wsl ubuntu container and also create a new clean project in hetzner cloud. Now the terraform setup is completed without a failure.

No i have try to add the new cluster to my rancher, but it is always on pending.

`kubectl get events`

```
root@k3s-control-plane-0:~# kubectl get events
LAST SEEN   TYPE      REASON                    OBJECT                     MESSAGE
25m         Normal    Starting                  node/k3s-agent-0           Starting kubelet.
25m         Warning   InvalidDiskCapacity       node/k3s-agent-0           invalid capacity 0 on image filesystem
25m         Normal    NodeHasSufficientMemory   node/k3s-agent-0           Node k3s-agent-0 status is now: NodeHasSufficientMemory
25m         Normal    NodeHasNoDiskPressure     node/k3s-agent-0           Node k3s-agent-0 status is now: NodeHasNoDiskPressure
25m         Normal    NodeHasSufficientPID      node/k3s-agent-0           Node k3s-agent-0 status is now: NodeHasSufficientPID
25m         Normal    NodeAllocatableEnforced   node/k3s-agent-0           Updated Node Allocatable limit across pods
25m         Normal    Starting                  node/k3s-agent-0           Starting kube-proxy.
25m         Normal    NodeReady                 node/k3s-agent-0           Node k3s-agent-0 status is now: NodeReady
25m         Normal    RegisteredNode            node/k3s-agent-0           Node k3s-agent-0 event: Registered Node k3s-agent-0 in Controller
25m         Normal    Starting                  node/k3s-agent-1           Starting kubelet.
25m         Warning   InvalidDiskCapacity       node/k3s-agent-1           invalid capacity 0 on image filesystem
25m         Normal    NodeHasSufficientMemory   node/k3s-agent-1           Node k3s-agent-1 status is now: NodeHasSufficientMemory
25m         Normal    NodeHasNoDiskPressure     node/k3s-agent-1           Node k3s-agent-1 status is now: NodeHasNoDiskPressure
25m         Normal    NodeHasSufficientPID      node/k3s-agent-1           Node k3s-agent-1 status is now: NodeHasSufficientPID
25m         Normal    NodeAllocatableEnforced   node/k3s-agent-1           Updated Node Allocatable limit across pods
25m         Normal    Starting                  node/k3s-agent-1           Starting kube-proxy.
25m         Normal    NodeReady                 node/k3s-agent-1           Node k3s-agent-1 status is now: NodeReady
25m         Normal    RegisteredNode            node/k3s-agent-1           Node k3s-agent-1 event: Registered Node k3s-agent-1 in Controller
25m         Normal    Starting                  node/k3s-agent-2           Starting kubelet.
25m         Warning   InvalidDiskCapacity       node/k3s-agent-2           invalid capacity 0 on image filesystem
25m         Normal    NodeHasSufficientMemory   node/k3s-agent-2           Node k3s-agent-2 status is now: NodeHasSufficientMemory
25m         Normal    NodeHasNoDiskPressure     node/k3s-agent-2           Node k3s-agent-2 status is now: NodeHasNoDiskPressure
25m         Normal    NodeHasSufficientPID      node/k3s-agent-2           Node k3s-agent-2 status is now: NodeHasSufficientPID
25m         Normal    NodeAllocatableEnforced   node/k3s-agent-2           Updated Node Allocatable limit across pods
25m         Normal    Starting                  node/k3s-agent-2           Starting kube-proxy.
25m         Normal    NodeReady                 node/k3s-agent-2           Node k3s-agent-2 status is now: NodeReady
25m         Normal    RegisteredNode            node/k3s-agent-2           Node k3s-agent-2 event: Registered Node k3s-agent-2 in Controller
26m         Normal    Starting                  node/k3s-control-plane-0   Starting kubelet.
26m         Warning   InvalidDiskCapacity       node/k3s-control-plane-0   invalid capacity 0 on image filesystem
26m         Normal    NodeHasSufficientMemory   node/k3s-control-plane-0   Node k3s-control-plane-0 status is now: NodeHasSufficientMemory
26m         Normal    NodeHasNoDiskPressure     node/k3s-control-plane-0   Node k3s-control-plane-0 status is now: NodeHasNoDiskPressure
26m         Normal    NodeHasSufficientPID      node/k3s-control-plane-0   Node k3s-control-plane-0 status is now: NodeHasSufficientPID
26m         Normal    NodeAllocatableEnforced   node/k3s-control-plane-0   Updated Node Allocatable limit across pods
26m         Normal    Starting                  node/k3s-control-plane-0   Starting kube-proxy.
25m         Normal    NodeReady                 node/k3s-control-plane-0   Node k3s-control-plane-0 status is now: NodeReady
25m         Normal    RegisteredNode            node/k3s-control-plane-0   Node k3s-control-plane-0 event: Registered Node k3s-control-plane-0 in Controller
25m         Normal    Starting                  node/k3s-control-plane-1   Starting kubelet.
25m         Warning   InvalidDiskCapacity       node/k3s-control-plane-1   invalid capacity 0 on image filesystem
25m         Normal    NodeHasSufficientMemory   node/k3s-control-plane-1   Node k3s-control-plane-1 status is now: NodeHasSufficientMemory
25m         Normal    NodeHasNoDiskPressure     node/k3s-control-plane-1   Node k3s-control-plane-1 status is now: NodeHasNoDiskPressure
25m         Normal    NodeHasSufficientPID      node/k3s-control-plane-1   Node k3s-control-plane-1 status is now: NodeHasSufficientPID
25m         Normal    NodeAllocatableEnforced   node/k3s-control-plane-1   Updated Node Allocatable limit across pods
25m         Normal    Starting                  node/k3s-control-plane-1   Starting kube-proxy.
25m         Normal    NodeReady                 node/k3s-control-plane-1   Node k3s-control-plane-1 status is now: NodeReady
25m         Normal    RegisteredNode            node/k3s-control-plane-1   Node k3s-control-plane-1 event: Registered Node k3s-control-plane-1 in Controller
25m         Normal    Starting                  node/k3s-control-plane-2   Starting kubelet.
25m         Warning   InvalidDiskCapacity       node/k3s-control-plane-2   invalid capacity 0 on image filesystem
25m         Normal    NodeHasSufficientMemory   node/k3s-control-plane-2   Node k3s-control-plane-2 status is now: NodeHasSufficientMemory
25m         Normal    NodeHasNoDiskPressure     node/k3s-control-plane-2   Node k3s-control-plane-2 status is now: NodeHasNoDiskPressure
25m         Normal    NodeHasSufficientPID      node/k3s-control-plane-2   Node k3s-control-plane-2 status is now: NodeHasSufficientPID
25m         Normal    NodeAllocatableEnforced   node/k3s-control-plane-2   Updated Node Allocatable limit across pods
25m         Normal    Starting                  node/k3s-control-plane-2   Starting kube-proxy.
25m         Normal    NodeReady                 node/k3s-control-plane-2   Node k3s-control-plane-2 status is now: NodeReady
25m         Normal    RegisteredNode            node/k3s-control-plane-2   Node k3s-control-plane-2 event: Registered Node k3s-control-plane-2 in Controller
```

**Comment by xunleii** [comment]
I'm sorry for that, this behavior is "expected" but not documented.
All your nodes are currently `uninitialized` (which is describe by the taint `node.cloudprovider.kubernetes.io/uninitialized: true`), because they need the [hcloud-cloud-controller-manager](https://github.com/hetznercloud/hcloud-cloud-controller-manager). (see https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/ for more documentation about this subject)

This is due to the k3s flag `--kubelet-arg cloud-provider=external` (cf. https://github.com/xunleii/terraform-module-k3s/blob/master/examples/hcloud-k3s/k3s.tf#L16). In order to fix that, you have two choices:
- using the `cloud-controller-manager` from hetzner (I recommend it, because it gaves you the ability to annotate your node with some useful `labels` like `failure-domain.beta.kubernetes.io/region` or `failure-domain.beta.kubernetes.io/zone`, which can be used for high-availability applications on several availability zone). **Be careful**: this controller must only be used if your nodes are hosted on hetzner cloud. If you use another cloud provider or something else (vsphere for example), you must use the right `cloud-controller-manager`.
- removing the flags from the list.

**Comment by tinohager** [comment]
Okay I see. I'm probably a born tester for this project. 🤪 
Thanks for your quick feedback and great support.

Maybe you could publish another example that generates a normal cluster that can be used in Rachner without further ado - that would be really great. Of course I would like to test it again.

**Comment by xunleii** [comment]
All testers are welcome :wink:
Thanks too for your responses and for this issue; I need to write more documentation in order to make this project more easier to use and to debug

Also, I will try to add an example with a very simple cluster, on a less "exotic" provider (like GCP or AWS)
