### ISSUE TITLE
rename variable name to cluster_domain

### ISSUE THREAD

**Issue by fredleger** [xunleii/terraform-module-k3s#53]
I do think it will be clearer if `var.name` is renamed in `cluster_domain` or similar.

Get tricked by this until i realised that my services where all ending in `aws.cluster` :-)

**Comment by xunleii** [comment]
Oops, I don't know it was clear in my mind when I wrote that :thinking: ... So, `cluster_domain` or `cluster_name` seems clearly better than just `name` (even if it's [documented](https://github.com/xunleii/terraform-module-k3s#inputs)).
